Checks for maven and exits if it does not exist. 	modified:   configure 	modified:   configure.ac

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -621,7 +621,7 @@ ac_ct_CC
 EXEEXT
 OBJEXT
 appname
-maven
+MAVEN
 ant
 java
 javac
@@ -2569,12 +2569,12 @@ appname=cfmap
 set dummy mvn; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_maven+set}" = set; then
+if test "${ac_cv_path_MAVEN+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $maven in
+  case $MAVEN in
   [\\/]* | ?:[\\/]*)
-  ac_cv_path_maven="$maven" # Let the user override the test with a path.
+  ac_cv_path_MAVEN="$MAVEN" # Let the user override the test with a path.
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
@@ -2584,7 +2584,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_maven="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_path_MAVEN="$as_dir/$ac_word$ac_exec_ext"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -2595,16 +2595,22 @@ IFS=$as_save_IFS
   ;;
 esac
 fi
-maven=$ac_cv_path_maven
-if test -n "$maven"; then
-  { echo "$as_me:$LINENO: result: $maven" >&5
-echo "${ECHO_T}$maven" >&6; }
+MAVEN=$ac_cv_path_MAVEN
+if test -n "$MAVEN"; then
+  { echo "$as_me:$LINENO: result: $MAVEN" >&5
+echo "${ECHO_T}$MAVEN" >&6; }
 else
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
 fi
 
 
+echo $MAVEN
+if test "x$MAVEN" = "x"; then
+	  { { echo "$as_me:$LINENO: error: you need to have maven installed!" >&5
+echo "$as_me: error: you need to have maven installed!" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 # Extract the first word of "ant", so it can be a program name with args.
 set dummy ant; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -3407,7 +3413,7 @@ ac_ct_CC!$ac_ct_CC$ac_delim
 EXEEXT!$EXEEXT$ac_delim
 OBJEXT!$OBJEXT$ac_delim
 appname!$appname$ac_delim
-maven!$maven$ac_delim
+MAVEN!$MAVEN$ac_delim
 ant!$ant$ac_delim
 java!$java$ac_delim
 javac!$javac$ac_delim
@@ -3746,4 +3752,5 @@ if test "$no_create" != yes; then
   # would make configure fail if this is the last instruction.
   $ac_cs_success || { (exit 1); exit 1; }
 fi
+
 
